/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: serverlist.proto */

#ifndef PROTOBUF_C_serverlist_2eproto__INCLUDED
#define PROTOBUF_C_serverlist_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ServerList ServerList;
typedef struct ServerList__ServerInfo ServerList__ServerInfo;


/* --- enums --- */


/* --- messages --- */

struct  ServerList__ServerInfo
{
  ProtobufCMessage base;
  uint32_t id;
  ProtobufCBinaryData name;
  ProtobufCBinaryData category;
  ProtobufCBinaryData title;
  ProtobufCBinaryData queue;
  ProtobufCBinaryData population;
  uint32_t address;
  uint32_t port;
  uint32_t available;
  ProtobufCBinaryData unavailable_message;
  protobuf_c_boolean has_host;
  ProtobufCBinaryData host;
};
#define SERVER_LIST__SERVER_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_list__server_info__descriptor) \
, 0, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, {0,NULL}, 0, 0, 0, {0,NULL}, 0, {0,NULL} }


struct  ServerList
{
  ProtobufCMessage base;
  size_t n_servers;
  ServerList__ServerInfo **servers;
  uint32_t last_server_id;
  uint32_t sort_criterion;
};
#define SERVER_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_list__descriptor) \
, 0,NULL, 0, 0 }


/* ServerList__ServerInfo methods */
void   server_list__server_info__init
                     (ServerList__ServerInfo         *message);
/* ServerList methods */
void   server_list__init
                     (ServerList         *message);
size_t server_list__get_packed_size
                     (const ServerList   *message);
size_t server_list__pack
                     (const ServerList   *message,
                      uint8_t             *out);
size_t server_list__pack_to_buffer
                     (const ServerList   *message,
                      ProtobufCBuffer     *buffer);
ServerList *
       server_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_list__free_unpacked
                     (ServerList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ServerList__ServerInfo_Closure)
                 (const ServerList__ServerInfo *message,
                  void *closure_data);
typedef void (*ServerList_Closure)
                 (const ServerList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor server_list__descriptor;
extern const ProtobufCMessageDescriptor server_list__server_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_serverlist_2eproto__INCLUDED */
