/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: serverlist.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "serverlist.pb-c.h"
void   server_list__server_info__init
                     (ServerList__ServerInfo         *message)
{
  static const ServerList__ServerInfo init_value = SERVER_LIST__SERVER_INFO__INIT;
  *message = init_value;
}
void   server_list__init
                     (ServerList         *message)
{
  static const ServerList init_value = SERVER_LIST__INIT;
  *message = init_value;
}
size_t server_list__get_packed_size
                     (const ServerList *message)
{
  assert(message->base.descriptor == &server_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_list__pack
                     (const ServerList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_list__pack_to_buffer
                     (const ServerList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerList *
       server_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerList *)
     protobuf_c_message_unpack (&server_list__descriptor,
                                allocator, len, data);
}
void   server_list__free_unpacked
                     (ServerList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor server_list__server_info__field_descriptors[11] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queue",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, queue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "population",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, population),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "available",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unavailable_message",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ServerList__ServerInfo, unavailable_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ServerList__ServerInfo, has_host),
    offsetof(ServerList__ServerInfo, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_list__server_info__field_indices_by_name[] = {
  6,   /* field[6] = address */
  8,   /* field[8] = available */
  2,   /* field[2] = category */
  10,   /* field[10] = host */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  5,   /* field[5] = population */
  7,   /* field[7] = port */
  4,   /* field[4] = queue */
  3,   /* field[3] = title */
  9,   /* field[9] = unavailable_message */
};
static const ProtobufCIntRange server_list__server_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor server_list__server_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerList.ServerInfo",
  "ServerInfo",
  "ServerList__ServerInfo",
  "",
  sizeof(ServerList__ServerInfo),
  11,
  server_list__server_info__field_descriptors,
  server_list__server_info__field_indices_by_name,
  1,  server_list__server_info__number_ranges,
  (ProtobufCMessageInit) server_list__server_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_list__field_descriptors[3] =
{
  {
    "servers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ServerList, n_servers),
    offsetof(ServerList, servers),
    &server_list__server_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_server_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ServerList, last_server_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_criterion",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(ServerList, sort_criterion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_list__field_indices_by_name[] = {
  1,   /* field[1] = last_server_id */
  0,   /* field[0] = servers */
  2,   /* field[2] = sort_criterion */
};
static const ProtobufCIntRange server_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor server_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerList",
  "ServerList",
  "ServerList",
  "",
  sizeof(ServerList),
  3,
  server_list__field_descriptors,
  server_list__field_indices_by_name,
  1,  server_list__number_ranges,
  (ProtobufCMessageInit) server_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
