#!/bin/sh

# Allow app to operate detached from the game directory.
export APPIMAGE_MODE_ENABLED=1

# Make sure glib/libsecret schemas are read in.
export XDG_DATA_DIRS="$APPDIR/usr/share:${XDG_DATA_DIRS:-}"

exec "$APPDIR/usr/bin/tera_launcher_for_linux" "$@"
