#!/bin/sh

# Allow app to operate detached from the game directory.
export APPIMAGE_MODE_ENABLED=1

export GSETTINGS_SCHEMA_DIR="$APPDIR/usr/share/glib-2.0/schemas"
export GTK_USE_PORTAL=1
export XDG_CONFIG_HOME="$APPDIR/config"
export XDG_DATA_DIRS="$APPDIR/usr/share:${XDG_DATA_DIRS:-}"
export PATH="$APPDIR/usr/bin:${PATH:-}"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:${LD_LIBRARY_PATH:-}"
exec "$APPDIR/usr/bin/tera_launcher_for_linux" "$@"
